###START###
# Shortcuts
# Swipe Left (3): Switch to next/new workspace
# Alt_L + Swipe Left (3): Move window left by 50 pixels
# Super_L + Swipe Left (3): Switch to last active workspace
# Super_L + Alt_L + Swipe Left (3): Simulate left mouse button press (drag)
#
# Swipe Right (3): Switch to previous/last active workspace
# Alt_L + Swipe Right (3): Move window right by 50 pixels
# Super_L + Swipe Right (3): Switch to first active workspace
#
# Swipe Up (3): Left click + enable fullscreen
# Alt_L + Swipe Up (3): Move window up by 50 pixels
# Super_L + Swipe Up (3): Enable floating mode
# Super_L + Shift_L + Swipe Up (3): Move to workspace x
# Super_L + Alt_L + Swipe Up (3): Rename workspace
# Shift_L + Swipe Up (3): Toggle scratchpad
#
# Swipe Down (3): Click & disable fullscreen
# Alt_L + Swipe Down (3): Move window down by 50 pixels
# Super_L + Swipe Down (3): Disable floating mode
# Shift_L + Swipe Down (3): Toggle scratchpad
#
# Swipe Left (4): Switch to next active workspace
# Super_L + Swipe Left (4): Move window to next active/new workspace
#
# Swipe Right (4): Switch to previous workspace
# Super_L + Swipe Right (4): Move window to previous/last workspace
#
# Swipe Up (4): Launch Rofi app launcher
# Super_L + Swipe Up (4): Launch Windows Launcher
# Super_L + Shift_L + Swipe Up (4): Go to workspace x
# Super_L + Alt_L + Swipe Up (4): Rename workspace
#
# Swipe Down (4): Escape key
# Super_L + Swipe Down (4): Escape key
#
# Pinch In (4): Launch Windows Launcher
#
# Rotate Clockwise (2): Raise volume
# Rotate Counterclockwise (2): Lower volume
#
# Hold (3) + Super_L: Left mouse click
###END###

swipe:
  3: # Three-finger gestures
    left:
      command: "~/.config/fusuma/scripts/workspace.sh next"
      keypress:
        LEFTALT:
          command: 'i3-msg "move left 50px"'
        LEFTMETA:
          command: "~/.config/fusuma/scripts/workspace.sh last"
        "LEFTMETA+LEFTALT":
          command: 'xdotool mousedown 1'

    right:
      command: "~/.config/fusuma/scripts/workspace.sh prev"
      keypress:
        LEFTALT:
          command: 'i3-msg "move right 50px"'
        LEFTMETA:
          command: "~/.config/fusuma/scripts/workspace.sh first"

    up:
      command: 'xdotool click 1 && i3-msg fullscreen'
      keypress:
        LEFTALT:
          command: 'i3-msg "move up 50px"'
        LEFTMETA:
          command: 'i3-msg floating enable'
        "LEFTMETA+LEFTSHIFT":
          command: "~/.config/fusuma/scripts/workspace.sh rofi"
        "LEFTMETA+LEFTALT":
          command: "~/.config/fusuma/scripts/workspace.sh rename"
        LEFTSHIFT:
          command: 'i3-msg scratchpad show'

    down:
      command: 'xdotool click 1 && i3-msg fullscreen disable'
      keypress:
        LEFTALT:
          command: 'i3-msg "move down 50px"'
        LEFTMETA:
          command: 'i3-msg floating disable'
        LEFTSHIFT:
          command: 'i3-msg scratchpad show'

  4: # Four-finger gestures
    left:
      command: 'i3-msg workspace next'
      keypress:
        LEFTMETA:
          command: "~/.config/fusuma/scripts/workspace.sh move next"

    right:
      command: 'i3-msg workspace prev'
      keypress:
        LEFTMETA:
          command: "~/.config/fusuma/scripts/workspace.sh move prev"

    up:
      command: "~/.config/rofi/scripts/launcher.sh"
      keypress:
        LEFTMETA:
          command: "~/.config/rofi/scripts/launcher_win.sh"
        "LEFTMETA+LEFTSHIFT":
          command: "~/.config/fusuma/scripts/workspace.sh rofi"
        "LEFTMETA+LEFTALT":
          command: "~/.config/fusuma/scripts/workspace.sh rename"

    down:
      command: 'xdotool key Escape'
      keypress:
        LEFTMETA:
          command: 'xdotool key Escape'

pinch:
  4:
    in:
      command: "~/.config/rofi/scripts/launcher_win.sh"

rotate:
  2:
    clockwise:
      command: 'xdotool key XF86AudioRaiseVolume'
    counterclockwise:
      command: 'xdotool key XF86AudioLowerVolume'

hold:
  3:
    keypress:
      LEFTMETA:
        command: 'xdotool click 1'

# ================================
# Gesture Sensitivity / Timings
# ================================
threshold:
  swipe: 0.4
  pinch: 0.4
  rotate: 0.4

interval:
  swipe: 0.8
  pinch: 0.1
  rotate: 0.1
